algoritmo "semnome"
var
nome: caractere  idade, n1, n2,n3, n4, media: real
inicio

escreva("Nome do aluno: ")
leia(nome)
escreva("Idade do ",nome,": ")
leia(idade)
escreva("Nota da primeira unidade: ")
leia(n1)
escreva("Nota da segunda unidade: ")
leia(n2)
escreva("Nota da terceira unidade: ")
leia(n3)
escreva("Nota da quarta unidade: ")
leia(n4)
media<-(n1 + n2 + n3 + n4) / 4
escreval("A média do aluno ", nome, idade, " foi: ", media:1:1)

fimalgoritmo